# WHAS

In [1]:
import numpy as np
import deepsurv
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
import h5py
filename = 'C:/Users/ASUS/Dropbox/석사학위논문/DeepSurv-master/data/whas_train_test.h5'
f = h5py.File(filename, 'r')

#Get the HDF5 group
group_train = f['train']
group_test = f['test']

#Checkout what keys are inside that group.
for key in group_train.keys():
    print(key)

train_x = group_train['x'].value
train_t = group_train['t'].value
train_e = group_train['e'].value

test_x = group_test['x'].value
test_t = group_test['t'].value
test_e = group_test['e'].value

#Do whatever you want with data

#After you are done
f.close()

train_df = pd.DataFrame(train_x)
train_df['Time'] = np.int32(train_t)
train_df['Event'] = train_e

test_df = pd.DataFrame(test_x)
test_df['Time'] = np.int32(test_t)
test_df['Event'] = test_e

#censored number
c_number = train_df['Event'].value_counts()[0] + test_df['Event'].value_counts()[0]
feat_num = len(list(train_df.columns))
total_number = len(train_x) + len(test_x)
c_rate = (c_number / total_number) * 100

print("total_number : ", total_number)
print("feature_number : ", feat_num)
print("censored_number : ", c_number)
print("censored_rate : " , c_rate)

e
t
x
total_number :  1638
feature_number :  8
censored_number :  948
censored_rate :  57.87545787545788


C:\Users\ASUS\Anaconda3\lib\site-packages\h5py\_hl\dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)


In [4]:
#네번째 변수가 CHF
train_x

array([[ 1.     , 84.     ,  0.     , 22.44662,  1.     ,  1.     ],
       [ 0.     , 36.     ,  0.     , 31.64232,  0.     ,  1.     ],
       [ 0.     , 76.     ,  0.     , 46.4816 ,  0.     ,  1.     ],
       ...,
       [ 0.     , 83.     ,  1.     , 27.17021,  0.     ,  1.     ],
       [ 0.     , 77.     ,  1.     , 31.61786,  1.     ,  1.     ],
       [ 0.     , 69.     ,  0.     , 38.77338,  0.     ,  0.     ]],
      dtype=float32)

# SUPPORT

In [19]:
import h5py
filename = 'C:/Users/ASUS/Dropbox/석사학위논문/DeepSurv-master/data/support_train_test.h5'
f = h5py.File(filename, 'r')

#Get the HDF5 group
group_train = f['train']
group_test = f['test']

#Checkout what keys are inside that group.
for key in group_train.keys():
    print(key)

train_x = group_train['x'].value
train_t = group_train['t'].value
train_e = group_train['e'].value

test_x = group_test['x'].value
test_t = group_test['t'].value
test_e = group_test['e'].value

#Do whatever you want with data

#After you are done
f.close()

train_df = pd.DataFrame(train_x)
train_df['Time'] = np.int32(train_t)
train_df['Event'] = train_e

test_df = pd.DataFrame(test_x)
test_df['Time'] = np.int32(test_t)
test_df['Event'] = test_e

#censored number
c_number = train_df['Event'].value_counts()[0] + test_df['Event'].value_counts()[0]
feat_num = len(list(train_df.columns))
total_number = len(train_x) + len(test_x)
c_rate = (c_number / total_number) * 100

print("total_number : ", total_number)
print("feature_number : ", feat_num)
print("censored_number : ", c_number)
print("censored_rate : " , c_rate)

e
t
x
total_number :  8873
feature_number :  16
censored_number :  2837
censored_rate :  31.97340245689169


C:\Users\ASUS\Anaconda3\lib\site-packages\h5py\_hl\dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)


In [20]:
#당뇨의 유무는 다섯번째 변수
train_x[1]

array([ 79.66095   ,   1.        ,   0.        ,   1.        ,
         0.        ,   0.        ,   1.        ,  54.        ,
        67.        ,  16.        ,  38.        , 142.        ,
        10.        ,   0.89990234], dtype=float32)

# METABRIC

In [11]:
import h5py
filename = 'C:/Users/ASUS/Dropbox/석사학위논문/DeepSurv-master/data/metabric_IHC4_clinical_train_test.h5'
f = h5py.File(filename, 'r')

#Get the HDF5 group
group_train = f['train']
group_test = f['test']

#Checkout what keys are inside that group.
for key in group_train.keys():
    print(key)

train_x = group_train['x'].value
train_t = group_train['t'].value
train_e = group_train['e'].value

test_x = group_test['x'].value
test_t = group_test['t'].value
test_e = group_test['e'].value

#Do whatever you want with data

#After you are done
f.close()

train_df = pd.DataFrame(train_x)
train_df['Time'] = np.int32(train_t)
train_df['Event'] = train_e

test_df = pd.DataFrame(test_x)
test_df['Time'] = np.int32(test_t)
test_df['Event'] = test_e

#censored number
c_number = train_df['Event'].value_counts()[0] + test_df['Event'].value_counts()[0]
feat_num = len(list(train_df.columns))
total_number = len(train_x) + len(test_x)
c_rate = (c_number / total_number) * 100

print("total_number : ", total_number)
print("feature_number : ", feat_num)
print("censored_number : ", c_number)
print("censored_rate : " , c_rate)

e
t
x
total_number :  1904
feature_number :  11
censored_number :  801
censored_rate :  42.069327731092436


C:\Users\ASUS\Anaconda3\lib\site-packages\h5py\_hl\dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)


In [17]:
#7번째가 화학요법 여부
train_x[1]

array([ 5.2848816,  9.581043 , 10.20462  ,  5.6649704,  1.       ,
        0.       ,  0.       ,  1.       , 85.94     ], dtype=float32)

# GBSG

In [7]:
import h5py
filename = 'C:/Users/ASUS/Dropbox/석사학위논문/DeepSurv-master/data/gbsg_cancer_train_test.h5'
f = h5py.File(filename, 'r')

#Get the HDF5 group
group_train = f['train']
group_test = f['test']

#Checkout what keys are inside that group.
for key in group_train.keys():
    print(key)

train_x = group_train['x'].value #1545
train_t = group_train['t'].value
train_e = group_train['e'].value

test_x = group_test['x'].value #686
test_t = group_test['t'].value
test_e = group_test['e'].value


#After you are done
f.close()

train_df = pd.DataFrame(train_x)
train_df['Time'] = np.int32(train_t)
train_df['Event'] = train_e

test_df = pd.DataFrame(test_x)
test_df['Time'] = np.int32(test_t)
test_df['Event'] = test_e

#censored number
c_number = train_df['Event'].value_counts()[0] + test_df['Event'].value_counts()[0]
feat_num = len(list(train_df.columns))
total_number = len(train_x) + len(test_x)
c_rate = (c_number / total_number) * 100

print("total_number : ", total_number)
print("feature_number : ", feat_num)
print("censored_number : ", c_number)
print("censored_rate : " , c_rate)

e
t
x
total_number :  2232
feature_number :  9
censored_number :  965
censored_rate :  43.2347670250896


C:\Users\ASUS\Anaconda3\lib\site-packages\h5py\_hl\dataset.py:313: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  "Use dataset[()] instead.", H5pyDeprecationWarning)


# NWTCO

In [15]:
#nwtco 데이터 불러오기
nwtco = pd.read_csv('C:/Users/ASUS/Dropbox/석사학위논문/DeepSurv-master/data/nwtco.csv')
train_df = nwtco.drop('seqno', axis = 1)
train_df = train_df.rename(columns = {'rel':'Event', 'edrel':'Time'})

#censored number
c_number = train_df['Event'].value_counts()[0]
feat_num = len(list(train_df.columns))
total_number = len(train_df['Event'])
c_rate = (c_number / total_number) * 100

print("total_number : ", total_number)
print("feature_number : ", feat_num)
print("censored_number : ", c_number)
print("censored_rate : " , c_rate)

#data split
train_df, test_df = train_test_split(train_df, test_size = 0.2)
train_df, val_df = train_test_split(train_df, test_size = 0.2)

total_number :  4028
feature_number :  8
censored_number :  3457
censored_rate :  85.82423038728898


In [16]:
#두번째 변수가 중앙부가 넓지 않고 favorable 한지 여부
train_df

instit  histol  stage  study  Event  Time  age  in.subcohort
1466       1       1      1      3      0  3582   31             0
3901       1       1      3      4      0   642   38             0
1560       1       1      1      3      0  3343    8             0
855        1       1      1      3      0  4753   10             0
1387       1       1      1      3      1   144    7             0
...      ...     ...    ...    ...    ...   ...  ...           ...
2417       1       1      1      4      1   148   50             0
2047       1       1      1      4      0  2636   25             0
1231       2       2      4      3      1   172   67             0
2927       1       1      3      4      1   229   44             1
1636       1       1      2      3      0  3529   36             1

[2577 rows x 8 columns]

In [ ]:
Favorable histology: The cancer cells in these tumors don’t look quite normal, 
    but there is no anaplasia (see next paragraph). About 9 of 10 Wilms tumors have a favorable histology. 
    The chance of curing children with these tumors is very good.